homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -31.6
  longitude: -60.7083
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 18
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Argentina/Cordoba

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: everyday123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#mqtt:
#  broker: 192.168.1.107
#  port: 8883
#  client_id: home-assistant-mariano
#  keepalive: 60
#  #username: USERNAME
#  #password: PASSWORD
#  #certificate: /home/paulus/dev/addtrustexternalcaroot.crt
#  protocol: 3.1
#  #birth_message:
#  #  topic: 'hass/status'
#  #  payload: 'online'
#  #  qos: 1
#  #  retain: true
#  #will_message:
#  #  topic: 'hass/status'
#  #  payload: 'offline'
#  #  qos: 1
#  #  retain: true

# Weather Prediction
sensor:
  platform: yr

light:
  platform: hue
  host: 192.168.0.102

group:
  living: light.living_door,light.living_windows,light.kitchen


camera:
  - platform: rpi_camera
  - platform: foscam
    ip: 192.168.0.103
    port: 1500
    username: admin
    password: everyday123

  - platform: mjpeg
    mjpeg_url: http://192.168.0.103:1500/videostream.cgi?user=admin&pwd=everyday123&resolution=32&rate=1000
    name: Living Camera
    authentication: digest

  #- name: Paulus
  #  platform: generic
  #  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.demo_paulus.attributes.latitude }},{{ states.device_tracker.mariano.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.mariano.attributes.latitude }},{{ states.device_tracker.demo_paulus.attributes.longitude }}
  #  limit_refetch_to_url_change: true

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.103
  - platform: owntracks

zone:
  - name: Home
    latitude: -31.633429
    longitude: -60.690822
    radius: 100
    icon: mdi:account-multiple

automation:
  - alias: Turn on light every 40 seconds
    trigger:
      platform: time
      # Matches every hour at 5 seconds past whole
      seconds: /40
    action:
      service: light.turn_on
      entity_id: light.living_windows
      data:
        brightness: 120
        rgb_color: [255, 0, 0]

  - alias: Camera position
    trigger:
      - platform: state
        entity_id: input_select.camera_positions
    action:
      service: shell_command.set_camera_position
      data_template:
        pos: '{{ states.input_select.camera_positions.state }}'

shell_command:
  set_camera_position: 'curl hom-k "http://192.168.0.103:1500/decoder_control.cgi?command={{ pos }}&user=admin&pwd=everyday123"'

scene:
  - name: Energize
    entities:
      group.all_lights:
        state: on
        rgb_color: [255, 255, 255]
        brightness: 255
  - name: Red
    entities:
      group.all_lights:
        state: on
        rgb_color: [255, 0, 0]
        brightness: 100
  - name: Green
    entities:
      group.all_lights:
        state: on
        rgb_color: [0, 255, 0]
        brightness: 100

input_boolean:
  notify_home:
    name: Notify when someone arrives home
    initial: off
    icon: mdi:car

input_select:
  who_cooks:
    name: Who cooks today
    options:
     - Paulus
     - Anne Therese
    initial: Anne Therese
    icon: mdi:panda
  living_room_preset:
    options:
      - Visitors
      - Visitors with kids
      - Home Alone
  camera_positions:
    initial: 31
    options:
      - 31
      - 33
      - 35

input_slider:
  slider1:
    name: Slider 1
    initial: 30
    min: -20
    max: 35
    step: 1

switch:
  - platform: flux
    lights:
      - group.all_lights
    name: Fluxer
    # start_time: '7:00' # default to sunrise
    stop_time: '23:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    brightness: 200
    mode: xy

  #- platform: arduino
  #  pins:
  #    11:
  #      name: Fan Office
  #    12:
  #      name: Light Desk
  #      initial: true
  #      negate: true

ifttt:
  key: bUfBmBnWBQBbHZoVFClPhR

#arduino:
#  port: /dev/ttyACM0

script:
  flash_room1:
      alias: Flash Room1 On
      sequence:
        - alias: Light living door On
          service: homeassistant.turn_on
          data:
            entity_id: light.living_door
        - alias: Light living window Off
          service: homeassistant.turn_off
          data:
            entity_id: light.living_windows
        - delay:
            # time for flash light on
            seconds: 0.5

        - alias: Light living window On
          service: homeassistant.turn_on
          data:
            entity_id: light.living_windows
        - alias: Light living door Off
          service: homeassistant.turn_off
          data:
            entity_id: light.living_door
        - delay:
            # time for flash light on
            seconds: 0.5

        - alias: loop_room1
          service: script.turn_on
          data:
            entity_id: script.flash_room1

